name: Smoketest

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  install:
    runs-on: ubuntu-latest
    name: Prepare repo

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Restore dependencies cache
        uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies on cache miss
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Install project dependencies from cache
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit == 'true'

      - name: Cache node_modules for other runs
        uses: actions/cache@v2
        id: module-cache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ github.sha }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ github.sha }}-

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    name: Lint

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore dependencies cache
        uses: actions/cache@v2
        id: moduleCache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ github.sha }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ github.sha }}-

      - name: Lint using ESLint
        run: yarn lint

  formatting:
    runs-on: ubuntu-latest
    needs: [install]
    name: Verify formatting

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore dependencies cache
        uses: actions/cache@v2
        id: moduleCache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ github.sha }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ github.sha }}-

      - name: Verify formatting
        run: yarn format:check

  build:
    runs-on: ubuntu-latest
    needs: [lint, formatting]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Restore dependencies cache
        uses: actions/cache@v2
        id: moduleCache
        with:
          path: ./node_modules
          key: ${{ runner.os }}-node-modules-${{ github.sha }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-modules-${{ github.sha }}-

      - name: Build site
        run: yarn build:ci

      - name: Upload a compiled website
        uses: actions/upload-artifact@v2
        with:
          name: Compiled website
          path: public/

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        ### REMOVE BEFORE MERGING!!!!!!!!
        # if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: prod
          FOLDER: public
          CLEAN: true
